[package]
name = "proxy-caller"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10.10"
ic-agent = "0.37.1"
icrc-ledger-types = "0.1.6"
tokio = { version = "1.29", features = ["full"] }
serde = "1.0.204"
serde_json = "1.0.120"
